# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.

image: node:latest

cache:
    paths:
      - node_modules/

stages:
  - mavenBuild
  - mavenTest
  - htmlTest
  - autoDeploy

mavenBuild:
  stage: mavenBuild
  tags:
    - spring
  script:
    - cd gameZone
    - mvn package -B
    
mavenTest: 
  stage: mavenTest
  tags:  
      - spring
  script:  
      - cd gameZone
      - mvn test  
  artifacts:  
    paths:  
      - gameZone/target/*.jar               
 
#htmlTest: 
#  stage: htmlTest
#  tags:  
#      - spring
#  script:  
#      - cd gameZone/src/test/resources
#      - npm install  
#      - npm test
      
autoDeploy:
  stage: autoDeploy
  only:
    - master
  tags:
    - spring
  script:
    - cd gameZone
    - sudo rm -r /g11/resources/templates
    - sudo rm -r /g11/resources/static
    - sudo mv src/main/resources/templates /g11/resources/templates
    - sudo mv src/main/resources/static /g11/resources/static
    - mvn package
    - sudo mv target/*.jar /g11/gameZone.jar
    - sudo chmod -R 777 /g11
    - sudo systemctl stop gameZone.service
    - sudo systemctl start gameZone.service
