# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy

mavenbuild:
  stage: mavenbuild
  tags:
    - spring
  script:
    - sudo cd /g11
    - mvn package -B
    
maventest: 
  stage: maventest
  tags:  
      - spring
  script:  
      - sudo cd /g11
      - mvn test  
  artifacts:  
    paths:  
      - /g11/*.jar
      
autoDeploy:
  stage: autoDeploy
  tags:
    - spring
  script:
    - cd /g11
    - mvn package
    - sudo rm -r /g11/resources/templates
    - sudo rm -r /g11/resources/static
    - sudo mv target/*.jar /g11/gameZone.jar
    - sudo mv gameZone/src/main/resources/templates /gameZone/resources/templates
    - sudo mv gameZone/src/main/resources/static /gameZone/resources/static
    - sudo chmod -R 777 /g11
    - sudo systemctl stop gameZone.service
    - sudo systemctl start gameZone.service