# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.

# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - mavenBuild
  - mavenTest
  - build
  - test
#  - autoDeploy

cache:
      paths:
        - node_modules/

mavenBuild:
  stage: mavenBuild
  tags:
    - spring
  script:
    - cd gameZone
    - mvn package -B
    
mavenTest: 
  stage: mavenTest
  tags:  
      - spring
  script:  
      - cd gameZone
      - mvn test  
  artifacts:  
    paths:  
      - gameZone/target/*.jar
      
install_dependencies:
      stage: build
      tags:
        - docker
      script:
        - npm install
      artifacts:
        paths:
          - cd gameZone
          - node_modules/

    testing_testing:
      stage: test
      tags:
        - docker
      script: npm test                                
      
#autoDeploy:
#  stage: autoDeploy
#  tags:
#    - spring
#  script:
#    - cd /g11
#    - mvn package
#    - sudo rm -r /g11/resources/templates
#    - sudo rm -r /g11/resources/static
#    - sudo mv gameZone/target/*.jar /g11/gameZone.jar
#    - sudo mv gameZone/src/main/resources/templates /gameZone/resources/templates
#    - sudo mv gameZone/src/main/resources/static /gameZone/resources/static
#    - sudo chmod -R 777 /g11
#    - sudo systemctl stop gameZone.service
#    - sudo systemctl start gameZone.service