# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.

image: node:latest

stages:
  - mavenBuild
  - mavenTest
 - htmlTest
  - autoDeploy
  
cache:
      paths:
        - node_modules/



mavenBuild:
  stage: mavenBuild
  tags:
    - spring
  script:
    - cd gameZone
    - mvn package -B
    
mavenTest: 
  stage: mavenTest
  tags:  
      - spring
  script:  
      - cd gameZone
      - mvn test  
  artifacts:  
    paths:  
      - gameZone/target/*.jar               
      
 testing_testing:
      stage: htmlTest
      tags:
        - docker
      script: 
      - npm install
      - npm test 

      
autoDeploy:
  stage: autoDeploy
  only:
    - master
  tags:
    - spring
  script:
    - cd /g11
    - cd gameZone
    - mvn package
    - sudo rm -r /g11/resources/templates
    - sudo rm -r /g11/resources/static
    - sudo mv target/*.jar /g11/gameZone.jar
    - sudo mv src/main/resources/templates /gameZone/resources/templates
    - sudo mv src/main/resources/static /gameZone/resources/static
    - sudo chmod -R 777 /g11
    - sudo systemctl stop gameZone.service
    - sudo systemctl start gameZone.service